//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARKOCHBA
{


 public partial class WebForm
 {

  /// <summary>
  /// panelTitle control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Panel panelTitle;

  /// <summary>
  /// btnTitle control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Button btnTitle;

  /// <summary>
  /// current_question control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.TextBox current_question;

  /// <summary>
  /// panelY_IDK_N control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Panel panelY_IDK_N;

  /// <summary>
  /// btnY control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Button btnY;

  /// <summary>
  /// btnIDK control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Button btnIDK;

  /// <summary>
  /// btnN control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Button btnN;

  /// <summary>
  /// paneltMY_MN control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Panel paneltMY_MN;

  /// <summary>
  /// btnMY control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Button btnMY;

  /// <summary>
  /// btnMN control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Button btnMN;

  /// <summary>
  /// candidate_solution control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.TextBox candidate_solution;
 }
}
